In [3]:
import pandas as pd

In [18]:
metadata_final = pd.read_csv("./datasets/metadata-filtered/metadata_final_ale.csv")
metadata_final

,Unnamed: 0,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,...,misc,relative_results,url,city,cp,state,Cat_Id,Description,Group_Id,Group
0,0,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,NaN,34.058092,-118.292130,Korean restaurant,4.4,18,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x80c2c78249aba68f:0x35bf16ce61be751d', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Los Angeles,90005,CA,5,Korean restaurant,1,Comida
1,1,Ahi - R&D House,"Ahi - R&D House, 940 S Gilbert Rd #2, Gilbert,...",0x872ba9240f2eabb7:0x6539ede3ea401a19,NaN,33.332435,-111.791137,Korean restaurant,5.0,2,...,"{'Service options': ['Delivery', 'Takeout'], '...","['0x872baefd83cde281:0xcea7c0735ed506ae', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Gilbert,85296,AZ,5,Korean restaurant,1,Comida
2,2,Kim's Kitchen,"Kim's Kitchen, Above Palace Spa, 1727 S 316th ...",0x549057a7db40d70d:0xe085b6f6463ca410,NaN,47.318445,-122.311246,Korean restaurant,4.7,13,...,"{'Service options': ['Delivery', 'Takeout'], '...",NaN,https://www.google.com/maps/place//data=!4m2!3...,Federal Way,98003,WA,5,Korean restaurant,1,Comida
3,3,Kook Bin,"Kook Bin, 13069 Wisteria Dr, Germantown, MD 20874",0x89b62c3d880935df:0xfcc6c5f9e7e0a627,NaN,39.178581,-77.271384,Korean restaurant,4.2,27,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x89b62c3d880935df:0x79a91fe5b0017294', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Germantown,20874,MD,5,Korean restaurant,1,Comida
4,4,Toyose,"Toyose, 3814 Noriega St, San Francisco, CA 94122",0x8085878a8085d297:0xadf6a9f9923446f2,NaN,37.753200,-122.504702,Korean restaurant,4.5,14,...,"{'Service options': ['Delivery', 'Takeout', 'D...",NaN,https://www.google.com/maps/place//data=!4m2!3...,San Francisco,94122,CA,5,Korean restaurant,1,Comida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329532,329532,Eatfit Food Truck,"Eatfit Food Truck, 7777 N Heartland Dr, Coeur ...",0x5361c123a062e72b:0xe9238e78df994bf0,NaN,47.743831,-116.799903,Macrobiotic restaurant,4.5,2,...,"{'Service options': ['Delivery', 'Takeout'], '...",NaN,https://www.google.com/maps/place//data=!4m2!3...,Coeur d'Alene,83815,ID,419,Macrobiotic restaurant,1,Comida
329533,329533,Moobongri,"Moobongri, 1300 San Pedro St, Los Angeles, CA ...",0x80c2c7d2e76ad7d9:0xd40ca6f74f9c441a,NaN,34.032258,-118.254136,Soondae restaurant,4.1,8,...,{'Service options': ['Delivery']},"['0x80c2c78073cc019d:0x678e86acdfe52fa', '0x80...",https://www.google.com/maps/place//data=!4m2!3...,Los Angeles,90015,CA,424,Soondae restaurant,1,Comida
329534,329534,Cháo Đêm,"Cháo Đêm, 9754 Garden Grove Blvd, Garden Grove...",0x80dd28798611e063:0xc6f65143e5c71e18,NaN,33.772999,-117.962427,Porridge restaurant,3.8,236,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x80dd270cbc6fdd05:0x49edfc8bc513a022', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Garden Grove,92844,CA,360,Porridge restaurant,1,Comida
329535,329535,High Country Smokehouse,"High Country Smokehouse, 702 W Trimble Ave, Be...",0x87cec5581b8eb5e7:0x35cbfdf4a48a817f,NaN,36.371808,-93.580830,Offal barbecue restaurant,4.8,85,...,"{'Service options': ['Takeout', 'Delivery'], '...","['0x87cec5423182a445:0x9111f1233888eef5', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Berryville,72616,AR,433,Offal barbecue restaurant,1,Comida
329536,329536,Ana's House antojitos Y Micheladas,"Ana's House antojitos Y Micheladas, 3755 Shade...",0x886b4f8f79d2166d:0x41ba80c2d714c24,NaN,39.825452,-86.045364,Dance restaurant,4.5,67,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x886b4c1b86d95631:0x1e88267c3de50e6f', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Indianapolis,46226,IN,264,Dance restaurant,1,Comida

In [19]:
metadata_final_new = metadata_final
metadata_final_new

,Unnamed: 0,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,...,misc,relative_results,url,city,cp,state,Cat_Id,Description,Group_Id,Group
0,0,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,NaN,34.058092,-118.292130,Korean restaurant,4.4,18,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x80c2c78249aba68f:0x35bf16ce61be751d', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Los Angeles,90005,CA,5,Korean restaurant,1,Comida
1,1,Ahi - R&D House,"Ahi - R&D House, 940 S Gilbert Rd #2, Gilbert,...",0x872ba9240f2eabb7:0x6539ede3ea401a19,NaN,33.332435,-111.791137,Korean restaurant,5.0,2,...,"{'Service options': ['Delivery', 'Takeout'], '...","['0x872baefd83cde281:0xcea7c0735ed506ae', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Gilbert,85296,AZ,5,Korean restaurant,1,Comida
2,2,Kim's Kitchen,"Kim's Kitchen, Above Palace Spa, 1727 S 316th ...",0x549057a7db40d70d:0xe085b6f6463ca410,NaN,47.318445,-122.311246,Korean restaurant,4.7,13,...,"{'Service options': ['Delivery', 'Takeout'], '...",NaN,https://www.google.com/maps/place//data=!4m2!3...,Federal Way,98003,WA,5,Korean restaurant,1,Comida
3,3,Kook Bin,"Kook Bin, 13069 Wisteria Dr, Germantown, MD 20874",0x89b62c3d880935df:0xfcc6c5f9e7e0a627,NaN,39.178581,-77.271384,Korean restaurant,4.2,27,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x89b62c3d880935df:0x79a91fe5b0017294', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Germantown,20874,MD,5,Korean restaurant,1,Comida
4,4,Toyose,"Toyose, 3814 Noriega St, San Francisco, CA 94122",0x8085878a8085d297:0xadf6a9f9923446f2,NaN,37.753200,-122.504702,Korean restaurant,4.5,14,...,"{'Service options': ['Delivery', 'Takeout', 'D...",NaN,https://www.google.com/maps/place//data=!4m2!3...,San Francisco,94122,CA,5,Korean restaurant,1,Comida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329532,329532,Eatfit Food Truck,"Eatfit Food Truck, 7777 N Heartland Dr, Coeur ...",0x5361c123a062e72b:0xe9238e78df994bf0,NaN,47.743831,-116.799903,Macrobiotic restaurant,4.5,2,...,"{'Service options': ['Delivery', 'Takeout'], '...",NaN,https://www.google.com/maps/place//data=!4m2!3...,Coeur d'Alene,83815,ID,419,Macrobiotic restaurant,1,Comida
329533,329533,Moobongri,"Moobongri, 1300 San Pedro St, Los Angeles, CA ...",0x80c2c7d2e76ad7d9:0xd40ca6f74f9c441a,NaN,34.032258,-118.254136,Soondae restaurant,4.1,8,...,{'Service options': ['Delivery']},"['0x80c2c78073cc019d:0x678e86acdfe52fa', '0x80...",https://www.google.com/maps/place//data=!4m2!3...,Los Angeles,90015,CA,424,Soondae restaurant,1,Comida
329534,329534,Cháo Đêm,"Cháo Đêm, 9754 Garden Grove Blvd, Garden Grove...",0x80dd28798611e063:0xc6f65143e5c71e18,NaN,33.772999,-117.962427,Porridge restaurant,3.8,236,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x80dd270cbc6fdd05:0x49edfc8bc513a022', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Garden Grove,92844,CA,360,Porridge restaurant,1,Comida
329535,329535,High Country Smokehouse,"High Country Smokehouse, 702 W Trimble Ave, Be...",0x87cec5581b8eb5e7:0x35cbfdf4a48a817f,NaN,36.371808,-93.580830,Offal barbecue restaurant,4.8,85,...,"{'Service options': ['Takeout', 'Delivery'], '...","['0x87cec5423182a445:0x9111f1233888eef5', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Berryville,72616,AR,433,Offal barbecue restaurant,1,Comida
329536,329536,Ana's House antojitos Y Micheladas,"Ana's House antojitos Y Micheladas, 3755 Shade...",0x886b4f8f79d2166d:0x41ba80c2d714c24,NaN,39.825452,-86.045364,Dance restaurant,4.5,67,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x886b4c1b86d95631:0x1e88267c3de50e6f', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Indianapolis,46226,IN,264,Dance restaurant,1,Comida

In [20]:
metadata_final_new.drop(columns=['Group','Unnamed: 0',"Description","category"], axis=1, inplace=True)

In [22]:
metadata_final_new['city'] = metadata_final_new['city'].str.strip()

print(metadata_final_new['city'].unique())
print(cities_filtered['city'].unique())

['Los Angeles' 'Gilbert' 'Federal Way' ... 'Spring Mountain Rd' 'NJ 07206'
 'Rising Sun Ave']
['New York' 'Los Angeles' 'Chicago' ... 'Overton' 'Victor' 'Wrangell']

In [23]:
metadata_final_new.rename(columns={'state': 'state_id'}, inplace=True)
metadata_final_new

,name,address,gmap_id,description,latitude,longitude,avg_rating,num_of_reviews,price,hours,misc,relative_results,url,city,cp,state_id,Cat_Id,Group_Id
0,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,NaN,34.058092,-118.292130,4.4,18,NaN,"[['Thursday', '6:30AM–6PM'], ['Friday', '6:30A...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x80c2c78249aba68f:0x35bf16ce61be751d', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Los Angeles,90005,CA,5,1
1,Ahi - R&D House,"Ahi - R&D House, 940 S Gilbert Rd #2, Gilbert,...",0x872ba9240f2eabb7:0x6539ede3ea401a19,NaN,33.332435,-111.791137,5.0,2,NaN,"[['Wednesday', 'Closed'], ['Thursday', '11:30A...","{'Service options': ['Delivery', 'Takeout'], '...","['0x872baefd83cde281:0xcea7c0735ed506ae', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Gilbert,85296,AZ,5,1
2,Kim's Kitchen,"Kim's Kitchen, Above Palace Spa, 1727 S 316th ...",0x549057a7db40d70d:0xe085b6f6463ca410,NaN,47.318445,-122.311246,4.7,13,NaN,"[['Wednesday', '11AM–8PM'], ['Thursday', '11AM...","{'Service options': ['Delivery', 'Takeout'], '...",NaN,https://www.google.com/maps/place//data=!4m2!3...,Federal Way,98003,WA,5,1
3,Kook Bin,"Kook Bin, 13069 Wisteria Dr, Germantown, MD 20874",0x89b62c3d880935df:0xfcc6c5f9e7e0a627,NaN,39.178581,-77.271384,4.2,27,NaN,"[['Wednesday', '10AM–8PM'], ['Thursday', '10AM...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x89b62c3d880935df:0x79a91fe5b0017294', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Germantown,20874,MD,5,1
4,Toyose,"Toyose, 3814 Noriega St, San Francisco, CA 94122",0x8085878a8085d297:0xadf6a9f9923446f2,NaN,37.753200,-122.504702,4.5,14,NaN,"[['Wednesday', '6PM–12AM'], ['Thursday', '6PM–...","{'Service options': ['Delivery', 'Takeout', 'D...",NaN,https://www.google.com/maps/place//data=!4m2!3...,San Francisco,94122,CA,5,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329532,Eatfit Food Truck,"Eatfit Food Truck, 7777 N Heartland Dr, Coeur ...",0x5361c123a062e72b:0xe9238e78df994bf0,NaN,47.743831,-116.799903,4.5,2,NaN,"[['Wednesday', '11AM–3:30PM'], ['Thursday', '1...","{'Service options': ['Delivery', 'Takeout'], '...",NaN,https://www.google.com/maps/place//data=!4m2!3...,Coeur d'Alene,83815,ID,419,1
329533,Moobongri,"Moobongri, 1300 San Pedro St, Los Angeles, CA ...",0x80c2c7d2e76ad7d9:0xd40ca6f74f9c441a,NaN,34.032258,-118.254136,4.1,8,NaN,"[['Tuesday', '10AM–2PM'], ['Wednesday', '10AM–...",{'Service options': ['Delivery']},"['0x80c2c78073cc019d:0x678e86acdfe52fa', '0x80...",https://www.google.com/maps/place//data=!4m2!3...,Los Angeles,90015,CA,424,1
329534,Cháo Đêm,"Cháo Đêm, 9754 Garden Grove Blvd, Garden Grove...",0x80dd28798611e063:0xc6f65143e5c71e18,NaN,33.772999,-117.962427,3.8,236,$,"[['Tuesday', '10AM–2AM'], ['Wednesday', '10AM–...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x80dd270cbc6fdd05:0x49edfc8bc513a022', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Garden Grove,92844,CA,360,1
329535,High Country Smokehouse,"High Country Smokehouse, 702 W Trimble Ave, Be...",0x87cec5581b8eb5e7:0x35cbfdf4a48a817f,NaN,36.371808,-93.580830,4.8,85,$,"[['Tuesday', '11AM–8PM'], ['Wednesday', '11AM–...","{'Service options': ['Takeout', 'Delivery'], '...","['0x87cec5423182a445:0x9111f1233888eef5', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Berryville,72616,AR,433,1
329536,Ana's House antojitos Y Micheladas,"Ana's House antojitos Y Micheladas, 3755 Shade...",0x886b4f8f79d2166d:0x41ba80c2d714c24,NaN,39.825452,-86.045364,4.5,67,NaN,"[['Monday', '11AM–10PM'], ['Tuesday', '11AM–10...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x886b4c1b86d95631:0x1e88267c3de50e6f', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Indianapolis,46226,IN,264,1

In [24]:
#metadata_final_citis= metadata_final_new.merge(cities_filtered[['city', 'city_id']], on='city', how='left')
metadata_final_new = metadata_final_new.merge(cities_filtered[['city', 'state_id', 'city_id']], on=['city', 'state_id'], how='left')


metadata_final_new

,name,address,gmap_id,description,latitude,longitude,avg_rating,num_of_reviews,price,hours,misc,relative_results,url,city,cp,state_id,Cat_Id,Group_Id,city_id
0,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,NaN,34.058092,-118.292130,4.4,18,NaN,"[['Thursday', '6:30AM–6PM'], ['Friday', '6:30A...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x80c2c78249aba68f:0x35bf16ce61be751d', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Los Angeles,90005,CA,5,1,2.0
1,Ahi - R&D House,"Ahi - R&D House, 940 S Gilbert Rd #2, Gilbert,...",0x872ba9240f2eabb7:0x6539ede3ea401a19,NaN,33.332435,-111.791137,5.0,2,NaN,"[['Wednesday', 'Closed'], ['Thursday', '11:30A...","{'Service options': ['Delivery', 'Takeout'], '...","['0x872baefd83cde281:0xcea7c0735ed506ae', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Gilbert,85296,AZ,5,1,182.0
2,Kim's Kitchen,"Kim's Kitchen, Above Palace Spa, 1727 S 316th ...",0x549057a7db40d70d:0xe085b6f6463ca410,NaN,47.318445,-122.311246,4.7,13,NaN,"[['Wednesday', '11AM–8PM'], ['Thursday', '11AM...","{'Service options': ['Delivery', 'Takeout'], '...",NaN,https://www.google.com/maps/place//data=!4m2!3...,Federal Way,98003,WA,5,1,460.0
3,Kook Bin,"Kook Bin, 13069 Wisteria Dr, Germantown, MD 20874",0x89b62c3d880935df:0xfcc6c5f9e7e0a627,NaN,39.178581,-77.271384,4.2,27,NaN,"[['Wednesday', '10AM–8PM'], ['Thursday', '10AM...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x89b62c3d880935df:0x79a91fe5b0017294', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Germantown,20874,MD,5,1,NaN
4,Toyose,"Toyose, 3814 Noriega St, San Francisco, CA 94122",0x8085878a8085d297:0xadf6a9f9923446f2,NaN,37.753200,-122.504702,4.5,14,NaN,"[['Wednesday', '6PM–12AM'], ['Thursday', '6PM–...","{'Service options': ['Delivery', 'Takeout', 'D...",NaN,https://www.google.com/maps/place//data=!4m2!3...,San Francisco,94122,CA,5,1,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329534,Eatfit Food Truck,"Eatfit Food Truck, 7777 N Heartland Dr, Coeur ...",0x5361c123a062e72b:0xe9238e78df994bf0,NaN,47.743831,-116.799903,4.5,2,NaN,"[['Wednesday', '11AM–3:30PM'], ['Thursday', '1...","{'Service options': ['Delivery', 'Takeout'], '...",NaN,https://www.google.com/maps/place//data=!4m2!3...,Coeur d'Alene,83815,ID,419,1,373.0
329535,Moobongri,"Moobongri, 1300 San Pedro St, Los Angeles, CA ...",0x80c2c7d2e76ad7d9:0xd40ca6f74f9c441a,NaN,34.032258,-118.254136,4.1,8,NaN,"[['Tuesday', '10AM–2PM'], ['Wednesday', '10AM–...",{'Service options': ['Delivery']},"['0x80c2c78073cc019d:0x678e86acdfe52fa', '0x80...",https://www.google.com/maps/place//data=!4m2!3...,Los Angeles,90015,CA,424,1,2.0
329536,Cháo Đêm,"Cháo Đêm, 9754 Garden Grove Blvd, Garden Grove...",0x80dd28798611e063:0xc6f65143e5c71e18,NaN,33.772999,-117.962427,3.8,236,$,"[['Tuesday', '10AM–2AM'], ['Wednesday', '10AM–...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x80dd270cbc6fdd05:0x49edfc8bc513a022', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Garden Grove,92844,CA,360,1,258.0
329537,High Country Smokehouse,"High Country Smokehouse, 702 W Trimble Ave, Be...",0x87cec5581b8eb5e7:0x35cbfdf4a48a817f,NaN,36.371808,-93.580830,4.8,85,$,"[['Tuesday', '11AM–8PM'], ['Wednesday', '11AM–...","{'Service options': ['Takeout', 'Delivery'], '...","['0x87cec5423182a445:0x9111f1233888eef5', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Berryville,72616,AR,433,1,4850.0
329538,Ana's House antojitos Y Micheladas,"Ana's House antojitos Y Micheladas, 3755 Shade...",0x886b4f8f79d2166d:0x41ba80c2d714c24,NaN,39.825452,-86.045364,4.5,67,NaN,"[['Monday', '11AM–10PM'], ['Tuesday', '11AM–10...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x886b4c1b86d95631:0x1e88267c3de50e6f', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Indianapolis,46226,IN,264,1,36.0

In [558]:
metadata_final_new.rename(columns={'Cat_Id': 'cat_id'}, inplace=True)
metadata_final_new.rename(columns={'Group_Id': 'group_id'}, inplace=True)

metadata_final_new.drop(columns=['city','cp'], axis=1, inplace=True)

In [26]:
metadata_final_new.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 329539 entries, 0 to 329538
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   name              329538 non-null  object
 1   address           328804 non-null  object
 2   gmap_id           329539 non-null  object
 3   description       22923 non-null   object
 4   latitude          329539 non-null  float64
 5   longitude         329539 non-null  float64
 6   avg_rating        329539 non-null  float64
 7   num_of_reviews    329539 non-null  int64
 8   price             49840 non-null   object
 9   hours             251992 non-null  object
 10  misc              287702 non-null  object
 11  relative_results  269125 non-null  object
 12  url               329539 non-null  object
 13  city              328797 non-null  object
 14  cp                328804 non-null  object
 15  state_id          328272 non-null  object
 16  Cat_Id            329539 non-null  int64
 17  Group_Id          329539 non-null  int64
 18  city_id           252538 non-null  float64
dtypes: float64(4), int64(3), object(12)
memory usage: 50.3+ MB

In [27]:
metadata_final_new.shape

(329539, 19)

In [48]:

df_misc = metadata_final_new.loc[:, ['misc','gmap_id']].drop_duplicates()
df_misc

,misc,gmap_id
0,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x80c2c778e3b73d33:0xbdc58662a4a97d49
1,"{'Service options': ['Delivery', 'Takeout'], '...",0x872ba9240f2eabb7:0x6539ede3ea401a19
2,"{'Service options': ['Delivery', 'Takeout'], '...",0x549057a7db40d70d:0xe085b6f6463ca410
3,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x89b62c3d880935df:0xfcc6c5f9e7e0a627
4,"{'Service options': ['Delivery', 'Takeout', 'D...",0x8085878a8085d297:0xadf6a9f9923446f2
...,...,...
329534,"{'Service options': ['Delivery', 'Takeout'], '...",0x5361c123a062e72b:0xe9238e78df994bf0
329535,{'Service options': ['Delivery']},0x80c2c7d2e76ad7d9:0xd40ca6f74f9c441a
329536,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x80dd28798611e063:0xc6f65143e5c71e18
329537,"{'Service options': ['Takeout', 'Delivery'], '...",0x87cec5581b8eb5e7:0x35cbfdf4a48a817f
329538,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x886b4f8f79d2166d:0x41ba80c2d714c24

In [49]:
df_misc.to_csv("./datasets/metadata-filtered/misc.csv", index=False, sep=';')

In [75]:
df_misc = pd.read_csv("./datasets/metadata-filtered/misc.csv", sep=';')
df_misc

,misc,gmap_id
0,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x80c2c778e3b73d33:0xbdc58662a4a97d49
1,"{'Service options': ['Delivery', 'Takeout'], '...",0x872ba9240f2eabb7:0x6539ede3ea401a19
2,"{'Service options': ['Delivery', 'Takeout'], '...",0x549057a7db40d70d:0xe085b6f6463ca410
3,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x89b62c3d880935df:0xfcc6c5f9e7e0a627
4,"{'Service options': ['Delivery', 'Takeout', 'D...",0x8085878a8085d297:0xadf6a9f9923446f2
...,...,...
329532,"{'Service options': ['Delivery', 'Takeout'], '...",0x5361c123a062e72b:0xe9238e78df994bf0
329533,{'Service options': ['Delivery']},0x80c2c7d2e76ad7d9:0xd40ca6f74f9c441a
329534,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x80dd28798611e063:0xc6f65143e5c71e18
329535,"{'Service options': ['Takeout', 'Delivery'], '...",0x87cec5581b8eb5e7:0x35cbfdf4a48a817f
329536,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x886b4f8f79d2166d:0x41ba80c2d714c24

In [76]:
#limpiar nulos
df_misc = df_misc.dropna(subset=['misc'])
df_misc.shape

(287700, 2)

In [77]:
df_misc.to_csv("./datasets/metadata-filtered/miscotro.csv", index=False, sep=';')

In [78]:
df_misc_test = df_misc

In [79]:
#validamos si tenemos caracteres malos 

for misc in df_misc_test['misc']:
    try:
        misc_dict = eval(misc)
    except:
        print(misc)

In [80]:
#keys
keys = set()
for misc in df_misc['misc']:
    if isinstance(misc, str):
        misc_dict = eval(misc)
        keys.update(misc_dict.keys())


print(keys)

{'Planning', 'From the business', 'Popular for', 'Offerings', 'Crowd', 'Atmosphere', 'Payments', 'Amenities', 'Accessibility', 'Health & safety', 'Getting here', 'Dining options', 'Service options', 'Health and safety', 'Highlights'}

In [81]:
df_misc.iloc[0].misc

"{'Service options': ['Takeout', 'Dine-in', 'Delivery'], 'Accessibility': ['Wheelchair accessible entrance'], 'Offerings': ['Comfort food'], 'Amenities': ['Good for kids'], 'Atmosphere': ['Casual']}"

In [82]:
# Eliminamos Getting Here y Health and safety y Health & safety
#df_misc['misc'] = df_misc['misc'].apply(lambda x: {k: v if k not in ['Getting Here', 'Health and safety', 'Health & safety'] else {} for k, v in x.items()} if isinstance(x, dict) else x)

def clean_misc1(misc):
    if isinstance(misc, str):
        misc_dict = eval(misc)
        if 'Health & safety' in misc_dict:
            del misc_dict['Health & safety']
        return str(misc_dict)
    else:
        return misc

df_misc['misc'] = df_misc['misc'].apply(clean_misc1)

def clean_misc2(misc):
    if isinstance(misc, str):
        misc_dict = eval(misc)
        if 'Health and safety' in misc_dict:
            del misc_dict['Health and safety']
        return str(misc_dict)
    else:
        return misc

df_misc['misc'] = df_misc['misc'].apply(clean_misc2)

def clean_misc3(misc):
    if isinstance(misc, str):
        misc_dict = eval(misc)
        if 'Getting Here' in misc_dict:
            del misc_dict['Getting Here']
        return str(misc_dict)
    else:
        return misc

df_misc['misc'] = df_misc['misc'].apply(clean_misc3)

/var/folders/vr/lstpy99j3yv9_z9jr_pmd2_w0000gn/T/ipykernel_2307/518909219.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_misc['misc'] = df_misc['misc'].apply(clean_misc1)
/var/folders/vr/lstpy99j3yv9_z9jr_pmd2_w0000gn/T/ipykernel_2307/518909219.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_misc['misc'] = df_misc['misc'].apply(clean_misc2)
/var/folders/vr/lstpy99j3yv9_z9jr_pmd2_w0000gn/T/ipykernel_2307/518909219.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_misc['misc'] = df_misc['misc'].apply(clean_misc3)

In [83]:
df_misc

,misc,gmap_id
0,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x80c2c778e3b73d33:0xbdc58662a4a97d49
1,"{'Service options': ['Delivery', 'Takeout'], '...",0x872ba9240f2eabb7:0x6539ede3ea401a19
2,"{'Service options': ['Delivery', 'Takeout'], '...",0x549057a7db40d70d:0xe085b6f6463ca410
3,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x89b62c3d880935df:0xfcc6c5f9e7e0a627
4,"{'Service options': ['Delivery', 'Takeout', 'D...",0x8085878a8085d297:0xadf6a9f9923446f2
...,...,...
329532,"{'Service options': ['Delivery', 'Takeout'], '...",0x5361c123a062e72b:0xe9238e78df994bf0
329533,{'Service options': ['Delivery']},0x80c2c7d2e76ad7d9:0xd40ca6f74f9c441a
329534,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x80dd28798611e063:0xc6f65143e5c71e18
329535,"{'Service options': ['Takeout', 'Delivery'], '...",0x87cec5581b8eb5e7:0x35cbfdf4a48a817f
329536,"{'Service options': ['Takeout', 'Dine-in', 'De...",0x886b4f8f79d2166d:0x41ba80c2d714c24

In [84]:

def clean_misc(misc):
    if isinstance(misc, str):
        misc_dict = eval(misc)
        for key in misc_dict:
            new_values = [value.replace("-", "_").replace(" ", "_") for value in misc_dict[key]]
            misc_dict[key] = new_values
        return str(misc_dict)
    else:
        return misc

df_misc['misc'] = df_misc['misc'].apply(clean_misc)

/var/folders/vr/lstpy99j3yv9_z9jr_pmd2_w0000gn/T/ipykernel_2307/2114861624.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_misc['misc'] = df_misc['misc'].apply(clean_misc)

In [85]:
df_misc

,misc,gmap_id
0,"{'Service options': ['Takeout', 'Dine_in', 'De...",0x80c2c778e3b73d33:0xbdc58662a4a97d49
1,"{'Service options': ['Delivery', 'Takeout'], '...",0x872ba9240f2eabb7:0x6539ede3ea401a19
2,"{'Service options': ['Delivery', 'Takeout'], '...",0x549057a7db40d70d:0xe085b6f6463ca410
3,"{'Service options': ['Takeout', 'Dine_in', 'De...",0x89b62c3d880935df:0xfcc6c5f9e7e0a627
4,"{'Service options': ['Delivery', 'Takeout', 'D...",0x8085878a8085d297:0xadf6a9f9923446f2
...,...,...
329532,"{'Service options': ['Delivery', 'Takeout'], '...",0x5361c123a062e72b:0xe9238e78df994bf0
329533,{'Service options': ['Delivery']},0x80c2c7d2e76ad7d9:0xd40ca6f74f9c441a
329534,"{'Service options': ['Takeout', 'Dine_in', 'De...",0x80dd28798611e063:0xc6f65143e5c71e18
329535,"{'Service options': ['Takeout', 'Delivery'], '...",0x87cec5581b8eb5e7:0x35cbfdf4a48a817f
329536,"{'Service options': ['Takeout', 'Dine_in', 'De...",0x886b4f8f79d2166d:0x41ba80c2d714c24

In [86]:
import ast

# Define una lista vacía para guardar los valores únicos
valores_unicos = []

# Recorre cada fila del DataFrame
for misc in df_misc['misc']:
    
    # Si es una cadena, conviértela a diccionario
    if isinstance(misc, str):
        misc_dict = ast.literal_eval(misc)
    elif isinstance(misc, dict):
        misc_dict = misc
    else:
        continue
    
    # Recorre cada valor del diccionario y agrega los valores únicos a la lista
    for value_list in misc_dict.values():
        valores_unicos.extend(value_list)
        
# Convierte la lista de valores únicos a un conjunto para eliminar duplicados
valores_unicos = set(valores_unicos)
valores_unicos

{'24_hour_public_transport_available',
 '24_hour_transit_available',
 'Accepts_reservations',
 'Active_military_discounts',
 'Alcohol',
 'All_inclusive',
 'All_you_can_eat',
 'Appointments_recommended',
 'Assisted_listening_devices',
 'Baggage_storage',
 'Bar_games',
 'Bar_on_site',
 'Bar_onsite',
 'Beer',
 'Braille_menu',
 'Breakfast',
 'Brunch_reservations_recommended',
 'Cash_only',
 'Casual',
 'Catering',
 'Checks',
 'Cheques',
 'Child_care',
 'Cocktails',
 'Coffee',
 'College_students',
 'Comfort_food',
 'Cosy',
 'Counter_service',
 'Cozy',
 'Credit_cards',
 'Curbside_pickup',
 'Dancing',
 'Debit_cards',
 'Delivery',
 'Dessert',
 'Dine_in',
 'Dinner',
 'Dinner_reservations_recommended',
 'Drive_through',
 'Family_friendly',
 'Fast_service',
 'Fireplace',
 'Food',
 'Food_at_bar',
 'Gender_neutral_restroom',
 'Gender_neutral_toilets',
 'Good_discounts',
 'Good_for_kids',
 'Good_for_working_on_laptop',
 'Great_bar_food',
 'Great_beer_selection',
 'Great_cocktails',
 'Great_coffee',
 'Great_dessert',
 'Great_tea_selection',
 'Great_wine_list',
 'Groups',
 'Halal_food',
 'Happy_hour_drinks',
 'Happy_hour_food',
 'Hard_liquor',
 'Healthy_options',
 'High_chairs',
 'Historic',
 'Identifies_as_Black_owned',
 'Identifies_as_veteran_led',
 'Identifies_as_women_led',
 'In_store_pick_up',
 'In_store_pickup',
 'In_store_shopping',
 'Karaoke',
 'Kids_menu',
 'Kids_toys',
 'LGBTQ_friendly',
 'Late_night_food',
 'Live_music',
 'Live_performances',
 'Lively',
 'Locals',
 'Lunch',
 'Lunch_reservations_recommended',
 'Membership_required',
 'NFC_mobile_payments',
 'No_contact_delivery',
 'On_site_services',
 'Online_appointments',
 'Online_care',
 'Online_classes',
 'Online_estimates',
 'Onsite_services',
 'Organic_dishes',
 'Outdoor_seating',
 'Outdoor_services',
 'Outside_food_allowed',
 'Passenger_loading_area',
 'Passport_photos',
 'Pay_ahead',
 'Play_area',
 'Prepared_foods',
 'Public_restroom',
 'Quick_bite',
 'Quick_visit',
 'Quiet',
 'Quiz_night',
 'Restaurant',
 'Restroom',
 'Romantic',
 'Rooftop_seating',
 'Salad_bar',
 'Same_day_delivery',
 'Seating',
 'Serves_local_specialty',
 'Small_plates',
 'Solo_dining',
 'Spirits',
 'Sport',
 'Sports',
 'Swimming_pool',
 'Takeaway',
 'Takeout',
 'Toilets',
 'Tourists',
 'Transgender_safe_space',
 'Transgender_safespace',
 'Trending',
 'Trivia_night',
 'University_students',
 'Upmarket',
 'Upscale',
 'Usually_a_wait',
 'Vegetarian_options',
 'Wheelchair_accessible_car_park',
 'Wheelchair_accessible_elevator',
 'Wheelchair_accessible_entrance',
 'Wheelchair_accessible_lift',
 'Wheelchair_accessible_parking_lot',
 'Wheelchair_accessible_restroom',
 'Wheelchair_accessible_seating',
 'Wheelchair_accessible_toilet',
 'Wheelchair_rental',
 'Wi_Fi',
 'Wine'}

In [87]:
# Lista de valores a buscar
#valores = ['Good for kids', 'Wheelchair accessible entrance']
# Crear una lista de 1s y 0s para cada valor buscado
encodings = []
for valor in valores_unicos:
    encoding = df_misc['misc'].apply(lambda x: valor in str(x)).astype(int)
    encodings.append(encoding)
    
# Unir los encodings en un DataFrame
df_encodings = pd.concat(encodings, axis=1)

# Renombrar las columnas del DataFrame
df_encodings.columns = valores_unicos

In [88]:
df_encodings

,Cocktails,On_site_services,Lunch,Live_performances,All_you_can_eat,Delivery,Groups,Gender_neutral_toilets,Fireplace,Wheelchair_accessible_restroom,...,Brunch_reservations_recommended,Wheelchair_accessible_lift,Cheques,Great_bar_food,Comfort_food,No_contact_delivery,Trivia_night,Tourists,Counter_service,Dancing
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,0,1,0,0,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
4,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329532,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
329533,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
329534,0,0,1,0,0,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0
329535,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
329536,0,0,1,0,0,1,1,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [89]:
df_encodings['gmap_id'] = df_misc['gmap_id']
df_encodings

,Cocktails,On_site_services,Lunch,Live_performances,All_you_can_eat,Delivery,Groups,Gender_neutral_toilets,Fireplace,Wheelchair_accessible_restroom,...,Wheelchair_accessible_lift,Cheques,Great_bar_food,Comfort_food,No_contact_delivery,Trivia_night,Tourists,Counter_service,Dancing,gmap_id
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0x80c2c778e3b73d33:0xbdc58662a4a97d49
1,0,0,1,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0x872ba9240f2eabb7:0x6539ede3ea401a19
2,0,0,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0x549057a7db40d70d:0xe085b6f6463ca410
3,0,0,1,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0x89b62c3d880935df:0xfcc6c5f9e7e0a627
4,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0x8085878a8085d297:0xadf6a9f9923446f2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329532,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0x5361c123a062e72b:0xe9238e78df994bf0
329533,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0x80c2c7d2e76ad7d9:0xd40ca6f74f9c441a
329534,0,0,1,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0x80dd28798611e063:0xc6f65143e5c71e18
329535,0,0,1,0,0,1,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0x87cec5581b8eb5e7:0x35cbfdf4a48a817f
329536,0,0,1,0,0,1,1,0,0,0,...,0,0,0,1,0,0,0,0,0,0x886b4f8f79d2166d:0x41ba80c2d714c24

In [91]:
df_encodings.to_csv("./datasets/metadata-filtered/misc_gmap.csv",sep=';',index=False)

In [90]:
df_encodings.columns

Index(['Cocktails', 'On_site_services', 'Lunch', 'Live_performances',
       'All_you_can_eat', 'Delivery', 'Groups', 'Gender_neutral_toilets',
       'Fireplace', 'Wheelchair_accessible_restroom',
       ...
       'Wheelchair_accessible_lift', 'Cheques', 'Great_bar_food',
       'Comfort_food', 'No_contact_delivery', 'Trivia_night', 'Tourists',
       'Counter_service', 'Dancing', 'gmap_id'],
      dtype='object', length=144)

In [97]:
metadata_final_new

,name,address,gmap_id,description,latitude,longitude,avg_rating,num_of_reviews,price,hours,relative_results,url,cat_id,group_id,city_id
0,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,NaN,34.058092,-118.292130,4.4,18,NaN,"[['Thursday', '6:30AM–6PM'], ['Friday', '6:30A...","['0x80c2c78249aba68f:0x35bf16ce61be751d', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,5,1,2.0
1,Ahi - R&D House,"Ahi - R&D House, 940 S Gilbert Rd #2, Gilbert,...",0x872ba9240f2eabb7:0x6539ede3ea401a19,NaN,33.332435,-111.791137,5.0,2,NaN,"[['Wednesday', 'Closed'], ['Thursday', '11:30A...","['0x872baefd83cde281:0xcea7c0735ed506ae', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,5,1,182.0
2,Kim's Kitchen,"Kim's Kitchen, Above Palace Spa, 1727 S 316th ...",0x549057a7db40d70d:0xe085b6f6463ca410,NaN,47.318445,-122.311246,4.7,13,NaN,"[['Wednesday', '11AM–8PM'], ['Thursday', '11AM...",NaN,https://www.google.com/maps/place//data=!4m2!3...,5,1,460.0
3,Kook Bin,"Kook Bin, 13069 Wisteria Dr, Germantown, MD 20874",0x89b62c3d880935df:0xfcc6c5f9e7e0a627,NaN,39.178581,-77.271384,4.2,27,NaN,"[['Wednesday', '10AM–8PM'], ['Thursday', '10AM...","['0x89b62c3d880935df:0x79a91fe5b0017294', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,5,1,NaN
4,Toyose,"Toyose, 3814 Noriega St, San Francisco, CA 94122",0x8085878a8085d297:0xadf6a9f9923446f2,NaN,37.753200,-122.504702,4.5,14,NaN,"[['Wednesday', '6PM–12AM'], ['Thursday', '6PM–...",NaN,https://www.google.com/maps/place//data=!4m2!3...,5,1,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329534,Eatfit Food Truck,"Eatfit Food Truck, 7777 N Heartland Dr, Coeur ...",0x5361c123a062e72b:0xe9238e78df994bf0,NaN,47.743831,-116.799903,4.5,2,NaN,"[['Wednesday', '11AM–3:30PM'], ['Thursday', '1...",NaN,https://www.google.com/maps/place//data=!4m2!3...,419,1,373.0
329535,Moobongri,"Moobongri, 1300 San Pedro St, Los Angeles, CA ...",0x80c2c7d2e76ad7d9:0xd40ca6f74f9c441a,NaN,34.032258,-118.254136,4.1,8,NaN,"[['Tuesday', '10AM–2PM'], ['Wednesday', '10AM–...","['0x80c2c78073cc019d:0x678e86acdfe52fa', '0x80...",https://www.google.com/maps/place//data=!4m2!3...,424,1,2.0
329536,Cháo Đêm,"Cháo Đêm, 9754 Garden Grove Blvd, Garden Grove...",0x80dd28798611e063:0xc6f65143e5c71e18,NaN,33.772999,-117.962427,3.8,236,$,"[['Tuesday', '10AM–2AM'], ['Wednesday', '10AM–...","['0x80dd270cbc6fdd05:0x49edfc8bc513a022', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,360,1,258.0
329537,High Country Smokehouse,"High Country Smokehouse, 702 W Trimble Ave, Be...",0x87cec5581b8eb5e7:0x35cbfdf4a48a817f,NaN,36.371808,-93.580830,4.8,85,$,"[['Tuesday', '11AM–8PM'], ['Wednesday', '11AM–...","['0x87cec5423182a445:0x9111f1233888eef5', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,433,1,4850.0
329538,Ana's House antojitos Y Micheladas,"Ana's House antojitos Y Micheladas, 3755 Shade...",0x886b4f8f79d2166d:0x41ba80c2d714c24,NaN,39.825452,-86.045364,4.5,67,NaN,"[['Monday', '11AM–10PM'], ['Tuesday', '11AM–10...","['0x886b4c1b86d95631:0x1e88267c3de50e6f', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,264,1,36.0

In [104]:
metadata_final_new.drop(columns=["state_id","misc"], axis=1, inplace=True)

metadata_final_new.to_csv("./datasets/metadata-filtered/metada_final_yami.csv",sep=';',index=False)

In [105]:
metadata_final_new.columns

Index(['name', 'address', 'gmap_id', 'description', 'latitude', 'longitude',
       'avg_rating', 'num_of_reviews', 'price', 'hours', 'relative_results',
       'url', 'cat_id', 'city_id'],
      dtype='object')