En este notebook prepararemos los datos para ingestar en PowerBi y realizar luego el análisis por ciudad para efectuar las recomendaciones de instalación de nuevas unidades de negocios a nuestro cliente

In [1]:
# Importamos las librerias necesarias
import pandas as pd
import numpy as np

In [2]:
# Importamos el dataset a utilizar con los datos de los comercios
metadata = pd.read_csv(r"datasets_limpios\metadata_final.csv", delimiter=";", names= ["name","address", "gmap_id", "description", "latitude", "longitude", "category", "avg_rating","num_of_reviews","price","hours","misc","relative_results","url"])

In [3]:
# Visualizamos el dataframe
metadata

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,hours,misc,relative_results,url
0,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,NaN,34.058092,-118.292130,Korean restaurant,4.4,18,NaN,"[['Thursday', '6:30AM–6PM'], ['Friday', '6:30A...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x80c2c78249aba68f:0x35bf16ce61be751d', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
1,Vons Chicken,"Vons Chicken, 12740 La Mirada Blvd, La Mirada,...",0x80dd2b4c8555edb7:0xfc33d65c4bdbef42,NaN,33.916402,-118.010855,Restaurant,4.5,18,NaN,"[['Thursday', '11AM–9:30PM'], ['Friday', '11AM...","{'Service options': ['Outdoor seating', 'Curbs...",NaN,https://www.google.com/maps/place//data=!4m2!3...
2,Lena’s Beauty Nails Lashes Brows,"Lena’s Beauty Nails Lashes Brows, 657 NE Ventu...",0x87ec2481df6626b5:0xff5627745308ec2b,NaN,41.616310,-93.858345,Beauty salon,4.2,128,NaN,"[['Thursday', '9AM–7PM'], ['Friday', '9AM–7PM'...","{'Health & safety': ['Appointment required'], ...","['0x87ec20ce836cac57:0x83bd66577e9a7a32', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
3,Sigman’s Diner,"Sigman’s Diner, 517 Elk St, Gassaway, WV 26624",0x884bdf439ee0d6e3:0x16676d0a5982954d,NaN,38.672489,-80.774893,Diner,4.6,28,NaN,"[['Thursday', '7AM–2PM'], ['Friday', '7AM–2PM'...","{'Service options': ['Takeout', 'Dine-in', 'De...",['0x884bcf5834725e7d:0x537d8a1a05e15936'],https://www.google.com/maps/place//data=!4m2!3...
4,The Beauty Bar,"The Beauty Bar, 413 Lincoln St, Roseville, CA ...",0x809b2037e088215d:0xbd3cebbdb6533638,NaN,38.752340,-121.285424,Beauty salon,4.9,21,NaN,"[['Thursday', '9AM–8PM'], ['Friday', '9AM–8PM'...","{'Health & safety': ['Mask required', 'Staff w...","['0x809b2037fa451d37:0x15f7ae418a9c671f', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329532,Market Cafe,"Market Cafe, 2312 AR-367, Bald Knob, AR 72010",0x87d3a24c6b9f6b1b:0x9ea26cbe6dc7aad9,NaN,35.306025,-91.574052,American restaurant,4.4,178,$,"[['Monday', '6AM–8PM'], ['Tuesday', '6AM–8PM']...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x87d3a3b2fecb8a8b:0x6198f40100abdb31', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
329533,Las Playitas,"Las Playitas, 3001 AR-25B, Heber Springs, AR 7...",0x87d247cfd66dd153:0x915c7425736e865a,NaN,35.515762,-92.019176,Mexican restaurant,4.3,154,$,"[['Monday', '11AM–9:30PM'], ['Tuesday', '11AM–...","{'Service options': ['Curbside pickup', 'No-co...",NaN,https://www.google.com/maps/place//data=!4m2!3...
329534,La Casa Mexican Restaurant,"La Casa Mexican Restaurant, 14 Bee Branch Rd, ...",0x87d268b0fbbfd4b9:0xeec251970fae404c,NaN,35.384414,-92.215903,Mexican restaurant,4.5,76,$$,"[['Monday', '11AM–7PM'], ['Tuesday', '11AM–7PM...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x87d279d0d5c14cc3:0xf0f3164d7467bd5', '0x87...",https://www.google.com/maps/place//data=!4m2!3...
329535,Country Kitchen,"Country Kitchen, 701 Main St, Pangburn, AR 72121",0x87d24cd30b7695d1:0xdc25418ff311a6aa,Homey chain eatery serving breakfast all day &...,35.425678,-91.839200,American restaurant,4.5,78,$,"[['Monday', '6AM–2PM'], ['Tuesday', '6AM–2PM']...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x87d24cd14c2328ff:0x42797c7e42cd07ba', '0x8...",https://www.google.com/maps/place//data=!4m2!3...
329536,Palm Gardens,"Palm Gardens, 52 Elm St, Cortland, NY 13045",0x89da6b8177ee49d5:0xbc9dfc53722fe1,NaN,42.602261,-76.173393,Bar & grill,4.0,128,$,"[['Monday', '8AM–2AM'], ['Tuesday', '8AM–2AM']...","{'Service options': ['Takeout', 'Dine-in', 'De...","['0x89da6c739859e46b:0xce1188b0e281b5c1', '0x8...",https://www.google.com/maps/place//data=!4m2!3...

In [4]:
# Generamos una nueva columna con el Estado y codigo postal de cada negocio,
# extrayendola del campo de la dirección
metadata['CPST'] = metadata['address'].str.split(',').str[-1]

In [5]:
# Generamos una nueva columna con la ciudad, extrayendola del campo dirección
metadata['city'] = metadata['address'].str.split(',').str[-2]

In [6]:
# Generamos una columna solo con el CP
metadata["cp"] = metadata["CPST"].str.split(" ").str[-1]

In [7]:
# Generamos una columna colo con el Estado
metadata["state"] = metadata["CPST"].str.split(" ").str[-2]

In [9]:
# Eliminamos la columna temporal
metadata = metadata.drop(["CPST"],axis=1)

In [10]:
# Importamos la tabla de categorìas y grupos
categorias = pd.read_csv(r"datasets_limpios\categorias.csv")

In [11]:
# Visualizamos
categorias

     Cat_Id       Description  Group_Id        Group
0         0        Love hotel         0  Alojamiento
1         1             Motel         0  Alojamiento
2         2            Hostel         0  Alojamiento
3         3     Forest resort         0  Alojamiento
4         4  Travellers lodge         0  Alojamiento
..      ...               ...       ...          ...
529     529      Chinese food         1       Comida
530     530  National reserve         2         Ocio
531     531       Nudist club         2         Ocio
532     532      Western food         1       Comida
533     533       Indian food         1       Comida

[534 rows x 4 columns]

In [12]:
# Agregamos estos datos al dataframe de los comercios
metadata_con_tipo = pd.merge (metadata, categorias, left_on= "category", right_on= "Description")

In [13]:
# Visualizamos
metadata_con_tipo

,name,address,gmap_id,description,latitude,longitude,category,avg_rating,num_of_reviews,price,...,misc,relative_results,url,city,cp,state,Cat_Id,Description,Group_Id,Group
0,San Soo Dang,"San Soo Dang, 761 S Vermont Ave, Los Angeles, ...",0x80c2c778e3b73d33:0xbdc58662a4a97d49,NaN,34.058092,-118.292130,Korean restaurant,4.4,18,NaN,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x80c2c78249aba68f:0x35bf16ce61be751d', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Los Angeles,90005,CA,5,Korean restaurant,1,Comida
1,Ahi - R&D House,"Ahi - R&D House, 940 S Gilbert Rd #2, Gilbert,...",0x872ba9240f2eabb7:0x6539ede3ea401a19,NaN,33.332435,-111.791137,Korean restaurant,5.0,2,NaN,...,"{'Service options': ['Delivery', 'Takeout'], '...","['0x872baefd83cde281:0xcea7c0735ed506ae', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Gilbert,85296,AZ,5,Korean restaurant,1,Comida
2,Kim's Kitchen,"Kim's Kitchen, Above Palace Spa, 1727 S 316th ...",0x549057a7db40d70d:0xe085b6f6463ca410,NaN,47.318445,-122.311246,Korean restaurant,4.7,13,NaN,...,"{'Service options': ['Delivery', 'Takeout'], '...",NaN,https://www.google.com/maps/place//data=!4m2!3...,Federal Way,98003,WA,5,Korean restaurant,1,Comida
3,Kook Bin,"Kook Bin, 13069 Wisteria Dr, Germantown, MD 20874",0x89b62c3d880935df:0xfcc6c5f9e7e0a627,NaN,39.178581,-77.271384,Korean restaurant,4.2,27,NaN,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x89b62c3d880935df:0x79a91fe5b0017294', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Germantown,20874,MD,5,Korean restaurant,1,Comida
4,Toyose,"Toyose, 3814 Noriega St, San Francisco, CA 94122",0x8085878a8085d297:0xadf6a9f9923446f2,NaN,37.753200,-122.504702,Korean restaurant,4.5,14,NaN,...,"{'Service options': ['Delivery', 'Takeout', 'D...",NaN,https://www.google.com/maps/place//data=!4m2!3...,San Francisco,94122,CA,5,Korean restaurant,1,Comida
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329532,Eatfit Food Truck,"Eatfit Food Truck, 7777 N Heartland Dr, Coeur ...",0x5361c123a062e72b:0xe9238e78df994bf0,NaN,47.743831,-116.799903,Macrobiotic restaurant,4.5,2,NaN,...,"{'Service options': ['Delivery', 'Takeout'], '...",NaN,https://www.google.com/maps/place//data=!4m2!3...,Coeur d'Alene,83815,ID,419,Macrobiotic restaurant,1,Comida
329533,Moobongri,"Moobongri, 1300 San Pedro St, Los Angeles, CA ...",0x80c2c7d2e76ad7d9:0xd40ca6f74f9c441a,NaN,34.032258,-118.254136,Soondae restaurant,4.1,8,NaN,...,{'Service options': ['Delivery']},"['0x80c2c78073cc019d:0x678e86acdfe52fa', '0x80...",https://www.google.com/maps/place//data=!4m2!3...,Los Angeles,90015,CA,424,Soondae restaurant,1,Comida
329534,Cháo Đêm,"Cháo Đêm, 9754 Garden Grove Blvd, Garden Grove...",0x80dd28798611e063:0xc6f65143e5c71e18,NaN,33.772999,-117.962427,Porridge restaurant,3.8,236,$,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x80dd270cbc6fdd05:0x49edfc8bc513a022', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Garden Grove,92844,CA,360,Porridge restaurant,1,Comida
329535,High Country Smokehouse,"High Country Smokehouse, 702 W Trimble Ave, Be...",0x87cec5581b8eb5e7:0x35cbfdf4a48a817f,NaN,36.371808,-93.580830,Offal barbecue restaurant,4.8,85,$,...,"{'Service options': ['Takeout', 'Delivery'], '...","['0x87cec5423182a445:0x9111f1233888eef5', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Berryville,72616,AR,433,Offal barbecue restaurant,1,Comida
329536,Ana's House antojitos Y Micheladas,"Ana's House antojitos Y Micheladas, 3755 Shade...",0x886b4f8f79d2166d:0x41ba80c2d714c24,NaN,39.825452,-86.045364,Dance restaurant,4.5,67,NaN,...,"{'Service options': ['Takeout', 'Dine-in', 'De...","['0x886b4c1b86d95631:0x1e88267c3de50e6f', '0x8...",https://www.google.com/maps/place//data=!4m2!3...,Indianapolis,46226,IN,264,Dance restaurant,1,Comida

In [14]:
# Exportamos el archivo csv a ingestar en PowerBi para realizar los análisis
metadata_con_tipo.to_csv("metadata_powerbi.csv")